apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"no-token","namespace":"venus"},"spec":{"containers":[{"image":"registry.k8s.io/pause:3.9","name":"c"}]}}
  creationTimestamp: "2026-08-05T04:43:03Z"
  generation: 1
  name: no-token
  namespace: venus
  resourceVersion: "33923"
  uid: b90bc565-cd22-45d0-8535-08273bf6d5cb
spec:
  containers:
  - image: registry.k8s.io/pause:3.9
    imagePullPolicy: IfNotPresent
    name: c
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: multi-node-cluster-worker5
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300

