apiVersion: v1
kind: Pod
metadata:
  labels:
    run: resource-1
  name: resource-1
spec:
  containers:
  - image: nginx:1.25
    name: resource-1
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
